package FinalProjectTestRun;

import java.awt.Color;

public class FinalProjectTester extends javax.swing.JFrame 
{

    /**
     * Creates new form FinalProjectTestRunTester
     */
    public FinalProjectTester() 
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        attackButton = new javax.swing.JButton();
        defendButton = new javax.swing.JButton();
        displayStatsButton = new javax.swing.JButton();
        buttonDescriptions = new javax.swing.JLabel();
        skillButton2 = new javax.swing.JButton();
        skillButton3 = new javax.swing.JButton();
        skillButton4 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        heroLabel = new javax.swing.JLabel();
        monsterLabel = new javax.swing.JLabel();
        skillButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Battle!");
        
        Hero hero1 = new Hero(26, 5, 1, true, false, "hi");
        Monster monster1 = new Monster(30, 8, 1, false, false, "hi");
        
        this.getContentPane().setBackground(Color.BLACK);
        jPanel1.setBackground(Color.GREEN);
        buttonDescriptions.setForeground(Color.WHITE); //Code format help from StackExchange

        attackButton.setText("Attack");
        attackListener attack = new attackListener(buttonDescriptions, hero1, monster1, this);
        attackButton.addActionListener(attack);
        attackButton.addMouseListener(attack);

        defendButton.setText("Defend");
        defendListener defend = new defendListener(buttonDescriptions, hero1, monster1, this);
        defendButton.addActionListener(defend);
        defendButton.addMouseListener(defend);

        displayStatsButton.setText("Show Stats");
        statListener stats = new statListener(buttonDescriptions, hero1);
        displayStatsButton.addActionListener(stats);
        displayStatsButton.addMouseListener(stats);
        
        skillButton1.setText("Healing Spray");
        skill1Listener skill1 = new skill1Listener(buttonDescriptions, hero1, monster1, this);
        skillButton1.addActionListener(skill1);
        skillButton1.addMouseListener(skill1);

        skillButton2.setText("Double Strike");
        skill2Listener skill2 = new skill2Listener(buttonDescriptions, hero1, monster1, this);
        skillButton2.addActionListener(skill2);
        skillButton2.addMouseListener(skill2);

        skillButton3.setText("Scan");
        skill3Listener skill3 = new skill3Listener(buttonDescriptions, hero1, monster1);
        skillButton3.addActionListener(skill3);
        skillButton3.addMouseListener(skill3);

        skillButton4.setText("Toxic Slash");
        skill4Listener skill4 = new skill4Listener(buttonDescriptions, hero1, monster1, this);
        skillButton4.addActionListener(skill4);
        skillButton4.addMouseListener(skill4);
        
        heroLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\A2mac\\OneDrive\\Documents\\Concordia\\2nd Year\\2nd Semester\\Intro to Computer Science\\Final Project\\Icons\\Icons\\HeroV2.png")); // NOI18N
        heroLabel.setText("Hero");
        heroLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        heroLabel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        monsterLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\A2mac\\OneDrive\\Documents\\Concordia\\2nd Year\\2nd Semester\\Intro to Computer Science\\Final Project\\Icons\\Icons\\GoblinV2.png")); // NOI18N
        monsterLabel.setText("Monster");
        monsterLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        monsterLabel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(heroLabel)
                .addGap(31, 31, 31)
                .addComponent(monsterLabel)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(109, Short.MAX_VALUE)
                .addComponent(heroLabel)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(monsterLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );


        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(attackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(defendButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(displayStatsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonDescriptions, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(skillButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(skillButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(skillButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(skillButton1))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {attackButton, defendButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(attackButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(defendButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(displayStatsButton)
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(skillButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(skillButton2)
                .addGap(30, 30, 30)
                .addComponent(skillButton3)
                .addGap(28, 28, 28)
                .addComponent(skillButton4)
                .addGap(29, 29, 29)
                .addComponent(buttonDescriptions, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        
        
        
    }// </editor-fold>                        
                                           

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) 
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FinalProjectTester.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FinalProjectTester.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FinalProjectTester.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FinalProjectTester.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() 
        {
            public void run() 
            {
                new FinalProjectTester().setVisible(true);
            }
        }); 
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton attackButton;
    private javax.swing.JLabel buttonDescriptions;
    private javax.swing.JButton defendButton;
    private javax.swing.JButton displayStatsButton;
    private javax.swing.JLabel heroLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel monsterLabel;
    private javax.swing.JButton skillButton1;
    private javax.swing.JButton skillButton2;
    private javax.swing.JButton skillButton3;
    private javax.swing.JButton skillButton4;
    // End of variables declaration                   
}

